name: Package

on:
  release:
    types: [published]
  workflow_dispatch:
  pull_request:

jobs:
  build_and_upload_wheel:
    name: Build and upload wheel
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Poetry
        run: |
          pipx install poetry==2.1.3
          pipx inject poetry "poetry-dynamic-versioning[plugin]==1.8.2"

      - run: poetry build
      - name: Test wheel
        if: github.event_name != 'release'
        run: |
            pipx install twine
            twine check dist/*
      - name: Upload wheel
        if: github.event_name == 'release'
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.ATOMICPYPI }}
