name: Package

on:
  push:
    branches:
      - master
  workflow_dispatch:
  pull_request:

jobs:
  build_and_upload_wheel:
    name: Build and upload wheel
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install poetry
        run: |
          python -m pip install poetry==1.1.12

      - name: Build wheel
        run: poetry build -f wheel

      - name: Configure poetry
        if: github.event_name == 'push'
        run: |
          poetry config pypi-token.pypi ${{ secrets.ATOMICPYPI }}

      - name: Upload wheel
        if: github.event_name == 'push'
        run: poetry publish
