name: Package

on:
  release: 
    types: [published]
  workflow_dispatch:
  pull_request:

jobs:
  build_and_upload_wheel:
    name: Build and upload wheel
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: pipx install poetry==1.3.2
      - run: pipx inject poetry poetry-dynamic-versioning==0.21.3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - run: poetry build
      - name: Test wheel
        if: github.event_name != 'release'
        run: |
            pipx install twine
            twine check dist/*
      - name: Upload wheel
        if: github.event_name == 'release'
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.ATOMICPYPI }}
