name: Test
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install poetry
        run: python -m pip install poetry==1.3.2 poethepoet==0.10.0

      - name: Install dependencies
        run: poetry install

      - name: Check formatting
        run: poe fmt-test

      - name: Check syntax
        run: poe flake

      - name: Run tests
        run: poe test

