name: Test

on:
  push:
    branches:
      - master
  workflow_dispatch:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python: ["3.10", "3.12"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "${{ matrix.python }}"

      - name: Install poetry
        run: python -m pip install poetry==2.1.3 poethepoet==0.34.0

      - name: Install dependencies
        run: poetry install

      - name: Check formatting
        run: poe fmt-test

      - name: Check syntax
        run: poe lint

      - name: Run tests
        run: poe test

      - name: Check doc build
        run: poe docs

      - name: Check type annotations
        run: poe types
