name: Test

on:
  push:
    branches:
      - master
  workflow_dispatch:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build Julia Package
        uses: julia-actions/setup-julia@v2
        uses: julia-actions/cache@v2
        uses: julia-actions/julia-buildpkg@v1
        with:
          project: atomic_physics/bloch

      - name: Install poetry
        run: python -m pip install poetry==1.3.2 poethepoet==0.24.4

      - name: Install dependencies
        run: poetry install -E bloch

      - name: Check formatting
        run: poe fmt-test

      - name: Check syntax
        run: poe lint

      - name: Run tests
        run: poe test

      - name: Check doc build
        run: poe docs

      - name: Check type annotations
        run: poe types

